# SAM CLI configuration file

version = 0.1

[default.global.parameters]
stack_name = "pontius-pilates-website"
region = "us-east-1"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "us-east-1"
s3_prefix = "pontius-pilates-website"
parameter_overrides = "Environment=\"production\" DomainName=\"\" CertificateArn=\"\""
image_repositories = []

[production]
[production.global.parameters]
stack_name = "pontius-pilates-website"

[production.build.parameters]
cached = true
parallel = true

[production.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
region = "us-east-1"
parameter_overrides = "Environment=production DomainName=\"\" CertificateArn=\"\""
